// ============================================================
// VocaStride — KELİME HAZNESİ (DOKUNULMAZ — kullanıcı kararı)
// format: [kelime, synonym, Türkçe karşılık]
// Bu dosya kaynak uygulamadan birebir aktarılmıştır.
// ============================================================
window.VOCA_WORDS = [
["abandon (v)", "leave", "terk etmek"],
["abolish (v)", "formally put an end", "yürürlükten kaldırmak"],
["absence (n)", "lack", "yokluk"],
["abstract (adj)", "conceptual", "soyut"],
["abundant (adj)", "plentiful", "bol, çok"],
["access (n)", "the right to use sth, enter a place, etc.", "giriş, erişim"],
["accommodate (v)", "lodge, give a bed", "barındırmak, kalacak yer vermek"],
["accompany (v)", "go or be with", "eşlik etmek"],
["accustomed (adj)", "familiar", "alışkın, alışmış"],
["achieve (v)", "accomplish", "başarmak"],
["acknowledge (v)", "admit; recognize", "kabul etmek; tanımak"],
["addiction (n)", "dependence", "bağımlılık"],
["adequate (adj)", "enough", "yeterli"],
["adjust (v)", "1. get used to 2. change slightly, correct", "1. uyum sağlamak 2. ayarlamak, düzeltmek"],
["administer (v)", "1. manage 2. apply", "1. idare etmek, yönetmek 2. (ilaç, tedavi vb.) vermek, uygulamak"],
["adopt (v)", "1. legally care for another's child 2. embrace", "1. evlat edinmek 2. benimsemek"],
["advance (n)", "1. progress 2. act of going forward", "1. gelişim 2. ilerleme"],
["adverse (adj)", "unfavourable", "olumsuz, kötü, ters"],
["affordable (adj)", "cheap", "ucuz, satın alınabilir"],
["aid (v)", "assist", "yardımcı olmak"],
["aim (n)", "objective", "amaç"],
["alert (adj)", "attentive", "tetikte, uyanık"],
["altitude (n)", "height, elevation", "yükseklik, rakım"],
["ample (adj)", "abundant", "bol, çok"],
["amusing (adj)", "entertaining", "eğlenceli, komik"],
["ancestor (n)", "forebear", "ata, ecdat"],
["annual (adj)", "yearly", "yılda bir, yıllık"],
["appeal (v)", "1. attract 2. request for help", "1. cazip gelmek, hitap etmek 2. yardım talebinde bulunmak"],
["appreciation (n)", "acknowledgment, thankfulness", "takdir, değerini anlama"],
["arise (v)", "1. emerge 2. get up; stand up", "1. ortaya çıkmak, kaynaklanmak 2. yataktan kalkmak; ayağa kalkmak"],
["artefact (n)", "relic", "tarihî öneme sahip insan yapımı nesne"],
["aspect (n)", "feature", "özellik, yön"],
["associate (v)", "link, connect in mind", "ilişkilendirmek, bağdaştırmak"],
["astonish (v)", "amaze", "şaşırtmak, hayrete düşürmek"],
["audible (adj)", "loud enough to hear", "duyulabilir"],
["avoid (v)", "stay away from", "kaçınmak"],
["aware (adj)", "conscious", "farkında, haberdar"],
["bankrupt (adj)", "unable to pay debts", "iflas etmiş, müflis"],
["barely (adv)", "hardly", "neredeyse hiç; güçlükle"],
["barren (adj)", "arid", "çorak, verimsiz"],
["basis (n)", "foundation", "temel"],
["bearable (adj)", "endurable", "katlanılabilir"],
["beg (v)", "1. plead 2. ask sb for money, esp. in the street", "1. yalvarmak 2. dilenmek"],
["benefit (n)", "advantage or help", "fayda"],
["beware (v)", "be careful", "sakınmak, uzak durmak"],
["bilingual (adj)", "speaking two languages", "iki dilli"],
["blend (n)", "mixture", "karışım, harman"],
["bold (adj)", "brave", "cesur"],
["briefly (adv)", "shortly", "kısaca"],
["broadly (adv)", "generally, on the whole", "genel olarak, esasen"],
["budget (n)", "financial plan", "bütçe"],
["burden (n)", "1. heavy load 2. duty; sth that causes stress", "1. yük 2. sorumluluk; sıkıntı"],
["candidate (n)", "applicant", "aday"],
["captivity (n)", "imprisonment", "esaret"],
["capture (v)", "1. catch, seize 2. photograph or film sb/sth", "1. yakalamak, el koymak, ele geçirmek 2. fotoğraf çekmek, görüntü almak"],
["cautiously (adv)", "carefully", "dikkatlice, tedbirli bir biçimde"],
["challenge (n)", "1. difficulty, obstacle 2. objection", "1. zorluk 2. itiraz, karşı çıkma"],
["charge (v)", "1. ask a price 2. give sb a task 3. accuse", "1. ücretlendirmek 2. görev vermek, sorumlu tutmak 3. suçlamak"],
["clumsy (adj)", "awkward, uncoordinated", "sakar, beceriksiz"],
["collaboratively (adv)", "cooperatively", "iş birliği hâlinde"],
["collapse (v)", "1. fall down 2. fail", "1. çökmek 2. başarısız olmak"],
["collide (v)", "crash", "çarp(ış)mak"],
["combat (v)", "fight", "savaşmak, mücadele etmek"],
["combine (v)", "join two things together", "birleş(tir)mek, kombine etmek"],
["commercial (adj)", "intended to make money", "ticari"],
["commit (v)", "1. do sth wrong 2. dedicate", "1. (suç, intihar vb.) işlemek/etmek 2. kendini adamak"],
["commodity (n)", "goods, product", "ticari mal"],
["compactible (adj)", "suited", "uyumlu"],
["comparatively (adv)", "relatively", "nispeten, kıyasla"],
["competent (adj)", "able", "yetkin, yetenekli"],
["competitive (adj)", "having a desire to win; involving competition", "rekabetçi; yarışmaya dayanan"],
["compile (v)", "collect", "derlemek, bir araya getirmek"],
["compose (v)", "1. constitute 2. write music", "1. oluşturmak, bir araya getirmek 2. beste yapmak"],
["compulsory (adj)", "obligatory", "zorunlu"],
["conceal (v)", "hide", "saklamak"],
["conclusive (adj)", "definitive", "nihai, kesin"],
["confirm (v)", "validate", "doğrulamak, onaylamak"],
["conflict (n)", "fight, clash", "anlaşmazlık, çatışma"],
["consecutively (adv)", "successively, serially", "peş peşe, arka arkaya"],
["consider (v)", "view, think of", "göz önünde bulundurmak, düşünmek"],
["considerable (adj)", "important, significant", "kayda değer"],
["consist (v)", "be made up of", "ibaret olmak, oluşmak"],
["constantly (adv)", "continually", "sürekli"],
["contamination (n)", "pollution", "kirlilik, kirletme"],
["content (n)", "composition", "içerik"],
["contribute (v)", "give sth to help to achieve", "katkıda bulunmak"],
["controversy (n)", "debate", "tartışma"],
["convenient (adj)", "useful, suitable", "uygun, elverişli, kullanışlı"],
["convince (v)", "make sb believe", "ikna etmek"],
["cover (v)", "1. spread sth over sth 2. include 3. provide enough money to pay for sth", "1. örtmek, kapamak 2. kapsamak, içermek 3. (masrafı) karşılamak"],
["crew (n)", "team, staff", "ekip, mürettebat"],
["crop (n)", "harvest, output", "ekin, hasat, mahsul"],
["crucial (adj)", "critical", "hayati, çok önemli"],
["cue (n)", "hint", "ipucu, işaret"],
["debt (n)", "money you owe", "borç"],
["deceive (v)", "trick", "kandırmak"],
["decent (adj)", "1. honest, morally acceptable 2. of an acceptable standard", "1. terbiyeli, düzgün 2. makul"],
["decline (v)", "1. decrease 2. refuse to accept", "1. azalmak 2. geri çevirmek"],
["defect (n)", "fault", "kusur, arıza"],
["deficient (adj)", "lacking", "eksik, noksan"],
["delay (v)", "postpone; slow down", "ertelemek; geciktirmek"],
["deliberately (adv)", "intentionally", "kasten, bile bile"],
["demanding (adj)", "challenging", "çaba gerektiren"],
["depiction (n)", "portrayal", "betimleme, tasvir"],
["deprivation (n)", "fact of not having sth you need", "yoksunluk, ihtiyaç"],
["derive (v)", "obtain from; come from", "edinmek, gelmek, kaynaklanmak"],
["deserve (v)", "be entitled to", "hak etmek"],
["desperately (adv)", "hopelessly", "çaresizce, ümitsizce"],
["destiny (n)", "fate", "kader"],
["devote (v)", "dedicate", "adamak"],
["diagnosis (n)", "detection", "teşhis"],
["digestion (n)", "process of absorbing food", "sindirim"],
["discrimination (n)", "unfair treatment", "ayrımcılık"],
["dismiss (v)", "1. reject 2. fire, sack", "1. reddetmek 2. kovmak"],
["disorder (n)", "1. illness 2. chaos", "1. hastalık 2. düzensizlik, karmaşa"],
["distant (adj)", "remote", "uzak"],
["distinct (adj)", "1. different 2. apparent", "1. farklı, ayrı 2. açık seçik, bariz"],
["distract (v)", "divert attention", "dikkatini dağıtmak, dikkatini başka yere çekmek"],
["diverse (adj)", "various", "farklı, çeşitli"],
["dramatically (adv)", "drastically", "çarpıcı ve beklenmedik şekilde"],
["dreadful (adj)", "horrible", "korkunç"],
["dull (adj)", "uninteresting", "sıkıcı, durgun"],
["durable (adj)", "long-lasting", "dayanıklı, uzun ömürlü"],
["eagerly (adv)", "keenly", "istekli bir şekilde"],
["edible (adj)", "fit to be eaten", "yenilebilir"],
["elaborately (adv)", "intricately, in a detailed way", "detaylı şekilde"],
["emerge (v)", "appear, originate", "ortaya çıkmak, belirmek"],
["emphasis (n)", "special attention, stress", "vurgu"],
["enable (v)", "make sth possible, allow", "olanak sağlamak, izin vermek"],
["encounter (v)", "meet by chance", "karşılaşmak"],
["endeavour (n)", "effort", "çaba, uğraş"],
["engaged (adj)", "1. having formally agreed to marry 2. busy", "1. nişanlı 2. meşgul"],
["ensure (v)", "make sure", "olmasını sağlamak, garantilemek"],
["entire (adj)", "complete; without nothing missing", "tüm, tam"],
["envious (adj)", "want to be as sb else or want to own things sb else has", "imrenen, gıpta eden"],
["evacuate (v)", "empty", "tahliye etmek, boşaltmak"],
["evenly (adv)", "equally", "eşit bir şekilde"],
["eventually (adv)", "finally", "sonunda, nihayet"],
["evident (adj)", "apparent", "belli, açık, ortada"],
["excavation (n)", "digging", "kazı"],
["exclusively (adv)", "only, particularly", "sadece, yalnızca"],
["excuse (n)", "reason, especially a false one", "bahane, mazeret"],
["expedition (n)", "exploration", "keşif gezisi, yolculuk"],
["expand (v)", "broaden, enlarge", "genişle(t)mek, büyü(t)mek, yay(ıl)mak"],
["expose (v)", "1. reveal 2. subject sb/sth to sth", "1. açığa/ortaya çıkarmak 2. maruz bırakmak"],
["extensive (adj)", "comprehensive", "kapsamlı"],
["extent (n)", "degree", "derece, kapsam, boyut"],
["extinct (adj)", "no longer existing", "nesli tükenmiş"],
["extraterrestrial (adj)", "from outer space", "dünya dışı"],
["extrovert (n)", "sociable person", "dışa dönük kişi"],
["failure (n)", "1. lack of success; sb or sth that is not successful 2. breakdown", "1. başarısızlık; başarısız kimse/şey 2. arıza"],
["faithful (adj)", "loyal", "sadık, bağlı"],
["fatigue (n)", "exhaustion", "yorgunluk, bitkinlik"],
["favour (n)", "1. help 2. approval or support", "1. yardım, iyilik 2. onaylama, destek"],
["fee (n)", "charge for service", "ücret, bedel"],
["fertile (adj)", "productive", "bereketli"],
["fever (n)", "1. temperature 2. excitement", "1. ateş 2. heyecan"],
["fierce (adj)", "violent", "şiddetli, azılı"],
["firmly (adv)", "1. rigidly 2. strongly, with determination", "1. sıkı, sıkıca 2. kesin olarak"],
["fit (adj)", "suitable", "uygun"],
["flaw (n)", "fault", "kusur"],
["flavour (n)", "taste", "tat"],
["forbid (v)", "prohibit", "yasaklamak"],
["foresee (v)", "predict", "ileriyi görmek, tahmin etmek"],
["formerly (adv)", "once, previously", "önceden, evvelden"],
["fortunate (adj)", "lucky", "şanslı"],
["fragile (adj)", "delicate", "kırılgan, narin"],
["futile (adj)", "vain", "anlamsız, nafile"],
["gadget (n)", "device", "cihaz, küçük alet"],
["gain (v)", "obtain", "elde etmek, kazanmak"],
["genuine (adj)", "1. authentic 2. sincere", "1. orijinal 2. içten"],
["glance (n)", "brief look", "bakış"],
["gradually (adv)", "bit by bit", "yavaşça"],
["grasp (n)", "1. grip 2. understanding", "1. yakalama, tutma 2. anlama, kavrama"],
["greed (n)", "selfish desire for more", "açgözlülük, hırs"],
["grief (n)", "great sadness", "keder, yas"],
["grip (n)", "grasp", "sıkıca tutma; anlama, idrak"],
["habitat (n)", "natural environment", "doğal ortam, yaşam alanı"],
["halt (n)", "stop", "durma, duraksama"],
["handle (v)", "deal with", "ele almak, halletmek"],
["hastily (adv)", "hurriedly", "aceleci bir şekilde"],
["hazard (n)", "peril, risk", "tehlike, risk"],
["heal (v)", "cure; recover", "iyileş(tir)mek"],
["herd (n)", "a group of animals of one kind", "sürü"],
["hesitate (v)", "pause in indecision", "tereddüt etmek"],
["hinder (v)", "slow down, limit", "engel olmak, köstek olmak"],
["hint (n)", "1. clue 2. advice, tip", "1. ima, ipucu 2. tavsiye"],
["hospitable (adj)", "welcoming", "misafirperver"],
["host (n)", "sb who has guests; a place that is home to an event", "ev sahibi"],
["hostility (n)", "unfriendliness", "düşmanlık"],
["humid (adj)", "damp", "nemli"],
["humorous (adj)", "funny", "esprili, komik"],
["identical (adj)", "alike, very similar", "aynı, özdeş"],
["identify (v)", "recognize, diagnose", "tanımak, teşhis etmek"],
["ignore (v)", "disregard", "görmezden gelmek"],
["illiterate (adj)", "unable to read or write", "okuma yazma bilmeyen"],
["immensely (adv)", "very much, extremely", "aşırı bir şekilde"],
["impair (v)", "weaken or harm", "bozmak, zarar vermek"],
["imperative (n)", "1. sth very important or urgent 2. command", "1. zorunluluk 2. emir"],
["impress (v)", "make sb feel admiration", "etkilemek, hayran bırakmak"],
["impulsively (adv)", "without any planning", "düşünmeden, güdüsel olarak"],
["indefinitely (adv)", "with no defined end, forever", "süresiz olarak"],
["indication (n)", "sign, evidence", "belirti, işaret, gösterge"],
["indifferent (adj)", "uninterested, aloof", "ilgisiz, kayıtsız"],
["infancy (n)", "1. babyhood 2. beginning", "1. bebeklik dönemi 2. başlangıç"],
["infer (v)", "conclude", "sonuca varmak, sonuç çıkarak"],
["inferior (adj)", "lesser", "ast, aşağı derecede olan"],
["infinite (adj)", "limitless", "sonsuz, sınırsız"],
["influence (n)", "impact", "etki"],
["inherently (adv)", "naturally, by birth", "doğası gereği"],
["inhabitant (n)", "resident", "(bir yerde) oturan kimse, sakin, yerli"],
["initially (adv)", "at first", "ilk olarak, başta, ilkin"],
["insight (n)", "awareness", "kavrama, anlama"],
["insane (adj)", "mentally ill; foolish", "deli(ce); anlamsız"],
["instantly (adv)", "at once", "derhâl, hemen"],
["intense (adj)", "deep and strong", "yoğun"],
["interact (v)", "communicate with each other; affect each other", "etkileşim içinde olmak"],
["internal (adj)", "inner", "içsel, dâhilî"],
["interpret (v)", "1. translate orally 2. explain the meaning of", "1. sözlü çeviri yapmak 2. yorumlamak, anlamını açıklamak"],
["inspire (v)", "1. encourage 2. give sb an idea for sth", "1. teşvik etmek, duygu aşılamak 2. ilham vermek"],
["inevitable (adj)", "unavoidable", "kaçınılmaz"],
["invest (v)", "put money into", "yatırım yapmak"],
["irrational (adj)", "illogical", "mantıksız, saçma"],
["irreversibly (adv)", "in a way that cannot be undone", "geri dönülmez biçimde"],
["item (n)", "part, article, object", "madde, parça, öge"],
["jointly (adv)", "together", "ortaklaşa"],
["justify (v)", "show that sth is right or reasonable", "haklı çıkarmak, doğrulamak"],
["labour (n)", "workforce; physical effort", "iş, emek"],
["lack (n)", "shortage", "yokluk, eksiklik"],
["latter (adj)", "1. second of two things 2. near or towards the end", "1. ikinci 2. sona yakın olan"],
["launch (n)", "1. act of starting sth 2. introduction of a product", "1. başlatma 2. piyasaya sürme"],
["legacy (n)", "inheritance; heritage", "miras"],
["lethal (adj)", "deadly", "ölümcül"],
["liable (adj)", "1. prone 2. responsible", "1. eğilimli 2. sorumlu"],
["maintain (v)", "1. continue to have 2. keep in good condition", "1. sürdürmek 2. bakımını yapmak"],
["manufacture (v)", "produce", "üretmek"],
["manually (adv)", "by hand", "elle"],
["massive (adj)", "huge", "büyük, devasa"],
["measure (n)", "an action to prevent sth", "önlem"],
["menace (n)", "threat, danger", "tehdit, tehlike"],
["mend (v)", "fix", "tamir etmek"],
["merciful (adj)", "forgiving", "insaflı"],
["mild (adj)", "not extreme, moderate", "ılıman, hafif, ılımlı"],
["miracle (n)", "very lucky or unexpected event", "mucize"],
["miserable (adj)", "1. unhappy 2. pitiful", "1. mutsuz, perişan 2. acınası"],
["misleading (adj)", "deceptive", "yanıltıcı"],
["misuse (v)", "abuse", "kötüye kullanmak"],
["moderate (adj)", "not extreme", "ölçülü, makul"],
["modest (adj)", "humble", "alçak gönüllü, mütevazı"],
["monitor (v)", "observe", "gözlemek, izlemek, kontrol etmek"],
["morally (adv)", "according to what is right or wrong", "ahlaken"],
["mortality (n)", "1. the fact that we will die 2. death rate", "1. ölümlülük 2. ölüm oranı"],
["mutually (adv)", "reciprocally", "karşılıklı olarak"],
["namely (adv)", "that is (to say)", "şöyle ki, yani"],
["native (adj)", "local; indigenous", "yerli; bir yere özgü"],
["naval (adj)", "nautical", "deniz kuvvetleriyle ilgili, denizcilik ve gemicilikle ilgili"],
["necessitate (v)", "require", "gerektirmek"],
["necessarily (adv)", "inevitably", "illa, ister istemez"],
["negligence (n)", "carelessness", "ihmalkârlık"],
["negotiate (v)", "discuss", "müzakere etmek"],
["notably (adv)", "particularly", "özellikle"],
["noticeable (adj)", "marked", "göze çarpan, dikkat çekici"],
["notify (v)", "inform", "bilgilendirmek"],
["novelty (n)", "innovation", "yenilik"],
["nutrient (n)", "essential ingredients in food", "besin maddesi"],
["obediently (adv)", "compliantly", "itaatkâr şekilde"],
["object (v)", "argue against", "karşı çıkmak, itiraz etmek"],
["obligation (n)", "duty, responsibility", "zorunluluk, yükümlülük"],
["obstacle (n)", "barrier, difficulty", "engel"],
["obtain (v)", "acquire, gain", "edinmek"],
["occupy (v)", "1. fill a space or time 2. reside 3. invade", "1. meşgul etmek 2. oturmak 3. işgal etmek"],
["occur (v)", "1. happen 2. exist, be found", "1. olmak, meydana gelmek 2. bulunmak"],
["odour (n)", "(unpleasant) smell", "(kötü) koku"],
["offence (n)", "1. crime 2. insult, assault", "1. suç 2. hakaret, saldırı"],
["omit (v)", "exclude", "dâhil etmemek, çıkarmak"],
["opponent (n)", "rival", "rakip, karşıt, muhalif"],
["opt (v)", "choose", "seçmek, karar kılmak"],
["outbreak (n)", "sudden happening, eruption", "patlak verme"],
["outcome (n)", "result", "sonuç"],
["outdated (adj)", "old-fashioned", "modası geçmiş, eski"],
["outlook (n)", "viewpoint", "bakış açısı"],
["output (n)", "sth produced", "ürün, çıktı"],
["outstanding (adj)", "exceptionally good", "göze çarpan, olağanüstü"],
["overcome (v)", "defeat, deal with", "üstesinden gelmek"],
["overwhelming (adj)", "1. very great 2. difficult to defeat", "1. çok büyük 2. ezici, galip gelen"],
["pace (n)", "speed", "hız, tempo"],
["partially (adv)", "partly", "kısmen"],
["participate (v)", "become involved in an activity", "katılmak, yer almak"],
["particularly (adv)", "specifically", "özellikle"],
["passionately (adv)", "enthusiastically", "tutkuyla"],
["peculiar (adj)", "1. strange 2. unique", "1. tuhaf 2. özgü"],
["permanently (adv)", "for good", "kalıcı olarak, daima"],
["persistently (adv)", "continuously", "ısrarlı şekilde, bıkıp usanmadan"],
["persuasive (adj)", "convincing", "ikna edici"],
["phase (n)", "stage", "aşama"],
["plain (adj)", "simple, clear", "sade, süssüz, net"],
["pose (v)", "1. cause, create 2. sit or stand for a photo", "1. teşkil etmek, oluşturmak 2. poz vermek"],
["positionally (adv)", "chiefly", "esasen, önellikle"],
["postpone (v)", "delay", "ertelemek"],
["potentially (adv)", "possibly", "potansiyel olarak"],
["practically (adv)", "1. almost 2. in reality", "1. hemen hemen 2. pratikte"],
["praise (v)", "compliment, express admiration", "övmek"],
["precaution (n)", "measure", "önlem"],
["precious (adj)", "valuable", "kıymetli"],
["precisely (adv)", "exactly", "tam olarak"],
["predator (n)", "animal that hunts", "yırtıcı hayvan"],
["predominantly (adv)", "mainly", "ağırlıklı olarak"],
["previous (adj)", "prior", "önceki, geçmiş"],
["primarily (adv)", "chiefly", "esasen, önellikle"],
["profoundly (adv)", "deeply, completely", "derinden, tam olarak, ciddi olarak"],
["profit (n)", "financial gain", "kâr"],
["promote (v)", "1. encourage 2. raise to a higher rank", "1. teşvik etmek 2. terfi ettirmek"],
["prone (adj)", "vulnerable, liable", "yatkın, meyilli"],
["proposal (n)", "offer", "öneri, teklif"],
["prove (v)", "show that sth is true", "kanıtlamak"],
["provide (v)", "supply", "sağlamak, temin etmek"],
["purchase (n)", "act of buying; sth you buy", "satın alma; satın alınan şey"],
["qualify (v)", "1. be eligible 2. entitle", "1. hak kazanmak, yeterlik kazanmak 2. hak vermek, yeterli kılmak"],
["randomly (adv)", "arbitrarily", "rastgele, gelişigüzel"],
["raw (adj)", "1. not cooked 2. in a natural state", "1. çiğ 2. ham, işlenmemiş"],
["rear (v)", "raise, bring up", "yetiştirmek, bakmak"],
["recall (v)", "recollect; remind", "hatırla(t)mak, anımsa(t)mak"],
["recipe (n)", "solution, formula", "çözüm, reçete"],
["reckless (adj)", "careless, heedless", "umursamaz, tedbirsiz"],
["recover (v)", "1. get well again 2. get back sth lost", "1. iyileşmek, düzelmek 2. geri almak, kurtarmak"],
["recruit (v)", "employ; enlist", "(işe) almak"],
["reduce (v)", "decrease", "azal(t)mak"],
["reflect (v)", "1. send light, heat, etc. back 2. demonstrate", "1. yansıtmak 2. göstermek, belirtmek"],
["regret (v)", "be upset about", "pişman olmak"],
["reject (v)", "say no to sth", "geri çevirmek, reddetmek"],
["reliable (adj)", "dependable", "güvenilir"],
["reluctantly (adv)", "unwillingly", "gönülsüzce"],
["remnant (n)", "remains", "kalıntı, artık"],
["replace (v)", "take the place of, put in place of", "yerine geçmek, yerine koymak"],
["require (v)", "1. necessitate 2. demand", "1. gerek duymak, gerektirmek 2. talep etmek"],
["resemble (v)", "look like", "benzemek, andırmak"],
["resist (v)", "fight against, oppose", "direnmek"],
["response (n)", "reaction", "yanıt, tepki"],
["restrict (v)", "limit", "kısıtlamak, sınırlandırmak"],
["retain (v)", "keep, hold", "muhafaza etmek, tutmak"],
["reveal (v)", "uncover", "meydana çıkarmak"],
["rigorous (adj)", "1. thorough, careful 2. strict", "1. dikkatli, özenli 2. çok sıkı"],
["rigid (adj)", "inflexible", "katı, sert"],
["rival (n)", "opponent", "rakip"],
["root (n)", "origin, basis", "kök, temel, ana neden"],
["roughly (adv)", "1. approximately 2. harshly, not gently", "1. yaklaşık olarak 2. kaba bir şekilde"],
["ruthless (adj)", "heartless, merciless", "acımasız, merhametsiz"],
["sack (v)", "fire", "işten atmak, kovmak"],
["scarce (adj)", "insufficient", "kıt, az"],
["schedule (n)", "agenda, timetable", "plan, program, çizelge"],
["severely (adv)", "harshly", "şiddetli bir şekilde"],
["shallow (adj)", "not deep", "sığ"],
["simply (adv)", "plainly, only, clearly", "basit şekilde, sırf, sadece"],
["slightly (adv)", "a little", "hafifçe, çok az"],
["smooth (adj)", "1. flat, even 2. happening without problem", "1. pürüzsüz 2. sorunsuz, arızasız"],
["solely (adv)", "merely", "yalnızca, sadece"],
["sound (adj)", "reasonable, logical", "akla yatkın, mantıklı"],
["span (n)", "1. duration 2. length, distance", "1. süre 2. uzunluk"],
["sparse (adj)", "thinly spread", "kıt, seyrek"],
["spectator (n)", "viewer", "seyirci, izleyici"],
["spill (v)", "(cause to) flow or drip", "dök(ül)mek"],
["split (v)", "1. divide 2. break up", "1. ayırmak, ayrılmak, bölüştürmek 2. ilişkiyi sonlandırmak"],
["spoil (v)", "1. ruin 2. decay", "1. mahvetmek, bozmak 2. çürümek, bozulmak"],
["starvation (n)", "hunger", "açlık, açlıktan ölme"],
["steady (adj)", "stable, unchanging", "sabit, değişmeyen"],
["stunning (adj)", "impressive; surprising", "çarpıcı, hayret verici"],
["substance (n)", "matter", "madde"],
["superior (adj)", "better, greater, higher than sth", "üstün"],
["survey (n)", "study", "araştırma, anket"],
["suspiciously (adv)", "in a way that causes distrust, with distrust", "şüpheli bir şekilde, şüpheyle"],
["swiftly (adv)", "quickly", "çabuk, hızlı bir şekilde"],
["tackle (v)", "address", "ele almak, çaresine bakmak"],
["tedious (adj)", "boring, dull", "sıkıcı, bıktırıcı"],
["tendency (n)", "inclination", "eğilim"],
["tension (n)", "a nervous feeling, strain", "gerilim"],
["thoroughly (adv)", "completely, in a detailed way", "baştan aşağı, detaylıca"],
["thrive (v)", "flourish", "gelişmek, başarılı olmak, zenginleşmek"],
["tough (adj)", "1. strong, sturdy 2. difficult", "1. sağlam, sert 2. zor, zorlu"],
["trait (n)", "characteristic", "kişisel özellik"],
["trigger (v)", "cause to happen", "tetiklemek, neden olmak"],
["trivial (adj)", "insignificant", "önemsiz, ufak tefek"],
["typically (adv)", "usually", "genel olarak, tipik şekilde"],
["undergo (v)", "be subjected to", "başından geçmek, maruz kalmak"],
["undertake (v)", "take on", "üstlenmek, girişmek"],
["urge (n)", "strong desire", "istek, dürtü"],
["urgent (adj)", "pressing, crucial", "acil"],
["utilize (v)", "make use of, employ", "yararlanmak, faydalanmak"],
["vacant (adj)", "empty", "(iş, oda, koltuk, vb.) boş, açık"],
["vague (adj)", "ambiguous", "belirsiz, muğlak"],
["vanish (v)", "disappear", "ortadan kaybolmak"],
["vary (v)", "range", "değişmek, çeşitlilik göstermek"],
["versatile (adj)", "all-round", "çok yönlü, çok amaçlı"],
["violate (v)", "break (a law, rule, etc.)", "(kural, hak vb.) çiğnemek, ihlal etmek"],
["virtually (adv)", "nearly", "neredeyse"],
["vivid (adj)", "colourful, clear", "canlı, parlak"],
["voluntary (adj)", "1. willing 2. done willingly", "1. gönüllü 2. isteyerek yapılan"],
["withdraw (v)", "1. move back 2. remove money from", "1. (savaştan, seçimden vb.) geri çekilmek 2. para çekmek"],
["wise (adj)", "sensible, knowledgeable", "akıllı, mantıklı, bilgece"],
["witness (n)", "sb who sees a crime or an accident", "tanık, şahit"],
["worship (v)", "revere, adore", "tapmak, ibadet etmek; çok sevmek"]
];
